version: '3.8'

services:
  api:
    build:
      context: ./api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./api/user-uploader-key.json:/app/user-uploader-key.json:ro

  video-analyzer:
    build:
      context: ./video-analyzer
    env_file: .env